#!/usr/bin/env bash

set -e -o pipefail; [[ -n "$DEBUG" ]] && set -x

GA_VERSION="${GA_VERSION:-__VERSION__}"
GA_IMAGE="${GA_IMAGE:-"docker.io/superbrothers/ga:${GA_VERSION}"}"

exec docker run "${GA_IMAGE}" "${@}"
# vim: ai ts=2 sw=2 et sts=2 ft=sh
